tasks:
  setup:
    - npm install -g npm@3
    - npm install
  tests:
    - npm run coverage
    - npm run lint
    - ./integration-test

coverage:
  path: coverage/cobertura-coverage.xml
  parser: cobertura
