#!/usr/bin/env bash
git fetch origin

if [ ! -d "./node_modules" ]; then
  npm install
fi

npm run prepublish > /dev/null

git apply test/fixtures/dummy.patch
./node_modules/.bin/eslint --no-ignore test/fixtures/dummy.js -f checkstyle > eslint-result.xml

has_failed=0

function print_error() {
  printf "\e[31m\e[1mError: $1 failed\e[0m\n" 1>&2
  has_failed=1
}

function print_success() {
  printf "\e[32m\e[1m$1 success\e[0m\n"
}

if cat eslint-result.xml | ./lint-filter.js; then
  print_error "stdin test"
elif [[ $(cat eslint-result.xml | ./lint-filter.js | grep -oc "no-console") != "1" ]]; then
  print_error "stdin output"
else
  print_success "args"
fi

if cat eslint-result.xml | ./lint-filter.js; then
  print_error "stdin test"
elif [[ $(cat eslint-result.xml | ./lint-filter.js | grep -oc "semi") != "1" ]]; then
  print_error "stdin output"
else
  print_success "args"
fi

if ./lint-filter.js eslint-result.xml; then
  print_error "file test"
elif [[ $(./lint-filter.js eslint-result.xml | grep -oc "semi") != "1" ]]; then
  print_error "args output"
else
  print_success "args"
fi

git checkout test/fixtures/dummy.js
rm -f eslint-result.xml

exit $has_failed
